# Generated by Django 5.0.3 on 2024-03-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qualifarsus", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Municipios_Elegiveis",
        ),
    ]
