# Generated by Django 5.0.3 on 2024-03-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualifarsus', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipios_Elegiveis',
        ),
    ]
