# Generated by Django 5.0.3 on 2024-03-26 12:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualifarsus", "0007_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uf_municipiosPreenchidos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verificacao_uf", models.BooleanField(default=False)),
                (
                    "data_registro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("cod_ibge", models.CharField(max_length=10)),
                ("nome_secretario", models.CharField(default=False, max_length=256)),
                ("email_secretario", models.CharField(default=" ", max_length=256)),
                ("telefone_secretario", models.CharField(max_length=14)),
                ("celular_secretario", models.CharField(max_length=15)),
                (
                    "nome_responsavel_af",
                    models.CharField(
                        blank=True, default=False, max_length=256, null=True
                    ),
                ),
                (
                    "email_responsavel_af",
                    models.CharField(
                        blank=True, default=" ", max_length=256, null=True
                    ),
                ),
                ("telefone_responsavel_af", models.CharField(max_length=14)),
                (
                    "celular_responsavel_af",
                    models.CharField(
                        blank=True, default=False, max_length=15, null=True
                    ),
                ),
                (
                    "nome_responsavel_ins",
                    models.CharField(default=False, max_length=256),
                ),
                (
                    "email_responsavel_ins",
                    models.CharField(default=" ", max_length=256),
                ),
                ("telefone_responsavel_ins", models.CharField(max_length=14)),
                ("celular_responsavel_ins", models.CharField(max_length=15)),
                ("observacoes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EquipamentosMat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipamento_uf", models.CharField(max_length=560)),
                (
                    "valor_unitario_uf",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantidade_uf", models.IntegerField(default=0)),
                (
                    "valor_total_uf",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "List_equip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qualifarsus.uf_municipiospreenchidos",
                    ),
                ),
            ],
        ),
    ]
