# Generated by Django 5.0.3 on 2024-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qualifarsus", "0008_uf_municipiospreenchidos_equipamentosmat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lista_itens_equipamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Equipamento", models.CharField(max_length=560)),
                ("Atividade", models.CharField(max_length=560)),
                ("UnidadeFuncional_Unidade", models.CharField(max_length=560)),
                ("Ambiente", models.CharField(max_length=560)),
                ("Classificação", models.CharField(max_length=560)),
            ],
        ),
        migrations.AlterField(
            model_name="uf_municipiospreenchidos",
            name="data_registro",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
