# Generated by Django 5.0.3 on 2024-03-25 14:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uf_municipio",
            name="celular_responsavel_af",
            field=models.CharField(blank=True, default=False, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="celular_responsavel_ins",
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="celular_secretario",
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="data_registro",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="email_responsavel_af",
            field=models.CharField(
                blank=True, default="noemail@example.com", max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="email_responsavel_ins",
            field=models.CharField(default="noemail@example.com", max_length=256),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="email_secretario",
            field=models.CharField(default="noemail@example.com", max_length=256),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="nome_responsavel_af",
            field=models.CharField(
                blank=True, default=False, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="nome_responsavel_ins",
            field=models.CharField(default=False, max_length=256),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="nome_secretario",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="telefone_responsavel_af",
            field=models.CharField(default=False, max_length=14),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="telefone_responsavel_ins",
            field=models.CharField(default=False, max_length=14),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="telefone_secretario",
            field=models.CharField(default=False, max_length=14),
        ),
        migrations.AddField(
            model_name="uf_municipio",
            name="verificacao_uf",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Equipamentos_mat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipamento_uf", models.CharField(max_length=560)),
                (
                    "valor_unitario_uf",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantidade_uf", models.IntegerField(default=0)),
                (
                    "valor_ttoal_uf",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "List_equip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.uf_municipio",
                    ),
                ),
            ],
        ),
    ]
